/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEmail' : IDL.Func([IDL.Text], [Message], []),
  'getAllEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyEmail' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Text });
  
  return IDL.Service({
    'addEmail' : IDL.Func([IDL.Text], [Message], []),
    'getAllEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyEmail' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };